name: Code Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint # Assuming you have a lint script in package.json

      - name: Run TypeScript Check
        run: npm run build # Assuming npm run build also performs type checking

      - name: Run Tests
        run: npm test # Assuming you have a test script in package.json
