name: Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version type to bump (major, minor, patch)'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push changes and create releases
      packages: write # Required to publish Docker images to GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for npm version to work correctly

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version and create tag
        id: bump_version
        run: |
          npm version ${{ github.event.inputs.version_type }}
          echo "new_version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Push changes and tags
        run: |
          git push
          git push --tags

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/ginden/docker-control-ha:latest
            ghcr.io/ginden/docker-control-ha:${{ steps.bump_version.outputs.new_version }}
          build-args: |
            BUILD_DATE=${{ github.event.repository.pushed_at }}
            VCS_REF=${{ github.sha }}
            VERSION=${{ steps.bump_version.outputs.new_version }}

      - name: Make Docker image public
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh package visibility ghcr.io/ginden/docker-control-ha --public

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.bump_version.outputs.new_version }}
          name: Release v${{ steps.bump_version.outputs.new_version }}
          body: |
            ## Release v${{ steps.bump_version.outputs.new_version }}

            This release includes:

            * Automated version bump
            * Docker image published to ghcr.io
            * GitHub Release created
          draft: false
          prerelease: false
